# Generated by Django 3.0.8 on 2021-01-05 07:43

from django.db import migrations, models
import reg_asistentes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.BigIntegerField(error_messages={'required': 'Identificacion es necesaria', 'unique': 'Ya existe la identificacion'}, unique=True, validators=[reg_asistentes.models.ValidateNumber])),
                ('nombres', models.TextField(error_messages={'required': 'Nombres es necesario'})),
                ('apellidos', models.TextField(error_messages={'required': 'Apellidos es necesario'})),
                ('correo_electronico', models.EmailField(error_messages={'required': 'correo es necesario', 'unique': 'Ya existe el correo'}, max_length=254, unique=True, validators=[reg_asistentes.models.ValidateEmail])),
                ('date_llegada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
